################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Application/User \
Drivers/CMSIS \
Drivers/STM32G4xx_HAL_Driver/Src \
Drivers/STM32G4xx_HAL_Driver \
MCSDK_v6.3.2-Full/MotorControl/MCSDK/MCLib/Any/Src \
MCSDK_v6.3.2-Full/MotorControl/MCSDK/MCLib/G4xx/Src \
Middlewares/MotorControl \
Src \
Startup \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/Core/Template/ARMv8-M \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/JTest/src \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform/ARMCC \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform/ARMCLANG \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform/GCC \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/platform \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/basic_math_tests \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/complex_math_tests \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/controller_tests \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/fast_math_tests \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/filtering_tests \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/intrinsics_tests \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/matrix_tests \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/statistics_tests \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/support_tests \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/src/transform_tests \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/DspLibTest_FVP_A5/RTE/CMSIS \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/DspLibTest_FVP_A5/RTE/Device/ARMCA5 \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/DspLibTest_FVP_A5 \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/BasicMathFunctions \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/ComplexMathFunctions \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/ControllerFunctions \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/FastMathFunctions \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/FilteringFunctions \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/HelperFunctions \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/Intrinsics \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/MatrixFunctions \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/StatisticsFunctions \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/SupportFunctions \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/src/TransformFunctions \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example/RTE/Device/ARMCM0 \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example/RTE/Device/ARMCM3 \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example/RTE/Device/ARMCM4_FP \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example/RTE/Device/ARMCM7_SP \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_class_marks_example \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example/RTE/Device/ARMCM0 \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example/RTE/Device/ARMCM3 \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example/RTE/Device/ARMCM4_FP \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example/RTE/Device/ARMCM7_SP \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_convolution_example \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example/RTE/Device/ARMCM0 \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example/RTE/Device/ARMCM3 \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example/RTE/Device/ARMCM4_FP \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example/RTE/Device/ARMCM7_SP \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_dotproduct_example \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example/RTE/Device/ARMCM0 \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example/RTE/Device/ARMCM3 \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example/RTE/Device/ARMCM4_FP \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example/RTE/Device/ARMCM7_SP \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_fft_bin_example \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example/RTE/Device/ARMCM0 \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example/RTE/Device/ARMCM3 \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example/RTE/Device/ARMCM4_FP \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example/RTE/Device/ARMCM7_SP \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_fir_example \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example/RTE/Device/ARMCM0 \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example/RTE/Device/ARMCM3 \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example/RTE/Device/ARMCM4_FP \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example/RTE/Device/ARMCM7_SP \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_graphic_equalizer_example \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example/RTE/Device/ARMCM0 \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example/RTE/Device/ARMCM3 \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example/RTE/Device/ARMCM4_FP \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example/RTE/Device/ARMCM7_SP \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_linear_interp_example \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example/RTE/Device/ARMCM0 \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example/RTE/Device/ARMCM3 \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example/RTE/Device/ARMCM4_FP \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example/RTE/Device/ARMCM7_SP \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_matrix_example \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example/RTE/Device/ARMCM0 \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example/RTE/Device/ARMCM3 \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example/RTE/Device/ARMCM4_FP \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example/RTE/Device/ARMCM7_SP \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_signal_converge_example \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example/RTE/Device/ARMCM0 \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example/RTE/Device/ARMCM3 \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example/RTE/Device/ARMCM4_FP \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example/RTE/Device/ARMCM7_SP \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_sin_cos_example \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example/RTE/Device/ARMCM0 \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example/RTE/Device/ARMCM3 \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example/RTE/Device/ARMCM4_FP \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example/RTE/Device/ARMCM7_SP \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Examples/ARM/arm_variance_example \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/PythonWrapper/cmsisdsp_pkg/src \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Source/BasicMathFunctions \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Source/CommonTables \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Source/ComplexMathFunctions \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Source/ControllerFunctions \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Source/FastMathFunctions \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Source/FilteringFunctions \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Source/MatrixFunctions \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Source/StatisticsFunctions \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Source/SupportFunctions \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/DSP/Source/TransformFunctions \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/Device/ST/STM32G4xx/Source/Templates/arm \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/Device/ST/STM32G4xx/Source/Templates/gcc \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/Device/ST/STM32G4xx/Source/Templates/iar \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/Device/ST/STM32G4xx/Source/Templates \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/cifar10/RTE/Device/ARMCM0 \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/cifar10/RTE/Device/ARMCM3 \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/cifar10/RTE/Device/ARMCM4_FP \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/cifar10/RTE/Device/ARMCM7_SP \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/gru/RTE/Device/ARMCM0 \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/gru/RTE/Device/ARMCM3 \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/gru/RTE/Device/ARMCM4_FP \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/gru/RTE/Device/ARMCM7_SP \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/RTE/Device/ARMCM0 \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/RTE/Device/ARMCM3 \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/RTE/Device/ARMCM4 \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/RTE/Device/ARMCM4_FP \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/RTE/Device/ARMCM7_SP \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/RTE/Device/STM32F411RETx \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/NN/NN_Lib_Tests/nn_test/Ref_Implementations \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/NN/Source/ActivationFunctions \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/NN/Source/ConvolutionFunctions \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/NN/Source/FullyConnectedFunctions \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/NN/Source/NNSupportFunctions \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/NN/Source/PoolingFunctions \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/NN/Source/SoftmaxFunctions \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/RTOS2/Source \
motorcontroller_fresh/claudeesc/Drivers/CMSIS/RTOS2/Template \
motorcontroller_fresh/claudeesc/Drivers/STM32G4xx_HAL_Driver/Src \
motorcontroller_fresh/claudeesc/MCSDK_v6.3.2-Full/MotorControl/MCSDK/MCLib/Any/Src \
motorcontroller_fresh/claudeesc/MCSDK_v6.3.2-Full/MotorControl/MCSDK/MCLib/G4xx/Src \
motorcontroller_fresh/claudeesc/STM32CubeIDE/Application/Startup \
motorcontroller_fresh/claudeesc/STM32CubeIDE/Application/User \
motorcontroller_fresh/claudeesc/Src \

